# Generated by Django 5.2.5 on 2025-08-19 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('pays', models.CharField(default='Burkina Faso', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('code_iso2', models.CharField(default='BF', max_length=2)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('population_propre', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duree_jours', models.PositiveIntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('villes', models.ManyToManyField(blank=True, related_name='circuits', to='gestion_cycle.ville')),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='SiteTouristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('localisation', models.CharField(blank=True, help_text='Coordonnées GPS ou adresse', max_length=255)),
                ('contact', models.CharField(blank=True, help_text='Téléphone, email, etc.', max_length=50)),
                ('heures_visite', models.CharField(blank=True, help_text='Ex: 09h00 - 17h00', max_length=100)),
                ('jours_visite', models.CharField(blank=True, help_text='Ex: Lundi - Samedi', max_length=100)),
                ('prix_visite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='sites/')),
                ('siteweb', models.URLField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude GPS', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude GPS', null=True)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='gestion_cycle.ville')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='EtapeCircuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('duree_etape', models.PositiveIntegerField(help_text='Durée en heures')),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='gestion_cycle.circuit')),
                ('sites', models.ManyToManyField(blank=True, to='gestion_cycle.sitetouristique')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_cycle.ville')),
            ],
            options={
                'verbose_name': 'Étape de circuit',
                'verbose_name_plural': 'Étapes de circuit',
                'ordering': ['ordre'],
                'unique_together': {('circuit', 'ordre')},
            },
        ),
    ]
