# Generated by Django 5.2.5 on 2025-08-19 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ville',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
