# Generated by Django 5.2.5 on 2025-08-19 13:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cycle', '0003_auto_20250819_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sitetouristique',
            options={},
        ),
        migrations.RemoveField(
            model_name='sitetouristique',
            name='heures_visite',
        ),
        migrations.RemoveField(
            model_name='sitetouristique',
            name='jours_visite',
        ),
        migrations.RemoveField(
            model_name='sitetouristique',
            name='localisation',
        ),
        migrations.RemoveField(
            model_name='sitetouristique',
            name='prix_visite',
        ),
        migrations.RemoveField(
            model_name='sitetouristique',
            name='siteweb',
        ),
        migrations.AddField(
            model_name='sitetouristique',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sitetouristique',
            name='horaire',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitetouristique',
            name='site_web',
            field=models.URLField(blank=True, default='ontb.bf', null=True),
        ),
        migrations.AddField(
            model_name='sitetouristique',
            name='tarif',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='sitetouristique',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitetouristique',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitetouristique',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='sitetouristique',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='sitetouristique',
            name='nom',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='sitetouristique',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='sites'),
        ),
        migrations.AddField(
            model_name='sitetouristique',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='gestion_cycle.categoriesite'),
        ),
    ]
