# Generated by Django 5.2.5 on 2025-08-21 11:50

import django.db.models.deletion
import gestion_cycle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cycle', '0004_categoriesite_alter_sitetouristique_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetouristique',
            name='photo',
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=gestion_cycle.models.site_image_upload_path)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gestion_cycle.sitetouristique')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
