# Generated by Django 5.2.5 on 2025-08-27 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cycle', '0006_guide_circuit_circuitetape'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='circuitetape',
            unique_together=set(),
        ),
    ]
