# Generated by Django 5.2.5 on 2025-08-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cycle', '0007_alter_circuitetape_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circuitetape',
            options={},
        ),
        migrations.RemoveField(
            model_name='circuitetape',
            name='jour',
        ),
        migrations.AddConstraint(
            model_name='circuitetape',
            constraint=models.UniqueConstraint(fields=('circuit', 'site'), name='unique_site_per_circuit'),
        ),
    ]
