# Generated by Django 5.2.5 on 2025-08-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cycle', '0010_circuit_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='map_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
